//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleGUI.SQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrgaSANItionEntities : DbContext
    {
        public OrgaSANItionEntities()
            : base("name=OrgaSANItionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Benutzer> Benutzer { get; set; }
        public virtual DbSet<Sanitage> Sanitage { get; set; }
        public virtual DbSet<Schulen> Schulen { get; set; }
        public virtual DbSet<Springertage> Springertage { get; set; }
        public virtual DbSet<Tage> Tage { get; set; }
    }
}
