//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleGUI.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tage
    {
        public int Tag_ID { get; set; }
        public string Datum { get; set; }
        public Nullable<int> Sani1 { get; set; }
        public Nullable<int> Sani2 { get; set; }
        public Nullable<int> Springer1 { get; set; }
        public Nullable<int> Springer2 { get; set; }
    
        public virtual Benutzer Benutzer { get; set; }
        public virtual Benutzer Benutzer1 { get; set; }
        public virtual Benutzer Benutzer2 { get; set; }
        public virtual Benutzer Benutzer3 { get; set; }
    }
}
